import { TRACKS, getTrack, DIFFICULTIES } from './tracks.js';
import { createRun, press, release, advance, summary } from './rhythm.js';
import { KitchenAudio } from './audio.js';
import KitchenRenderer from './render.js';

const RECORD_KEY = 'sizzle-sync.records.v1';
const SETTINGS_KEY = 'sizzle-sync.settings.v1';
const clone = value => { try { return JSON.parse(JSON.stringify(value)); } catch (_) { return null; } };
const safeRead = (key, fallback) => { try { const value = JSON.parse(localStorage.getItem(key) || 'null'); return value ?? fallback; } catch (_) { return fallback; } };
const safeWrite = (key, value) => { try { localStorage.setItem(key, JSON.stringify(value)); } catch (_) {} };

const savedSettings = safeRead(SETTINGS_KEY, {}); const settings = Object.assign({ volume: .72, muted: false, offset: 0, difficulty: 'normal' }, savedSettings && typeof savedSettings === 'object' && !Array.isArray(savedSettings) ? savedSettings : {});
settings.volume = Number.isFinite(Number(settings.volume)) ? Math.max(0, Math.min(1, Number(settings.volume))) : .72; settings.offset = Number.isFinite(Number(settings.offset)) ? Math.max(-200, Math.min(200, Number(settings.offset))) : 0; settings.difficulty = settings.difficulty === 'relaxed' ? 'relaxed' : 'normal'; settings.muted = settings.muted === true;
const savedRecords = safeRead(RECORD_KEY, {}); const records = savedRecords && typeof savedRecords === 'object' && !Array.isArray(savedRecords) ? savedRecords : {};
const canvas = document.getElementById('game-canvas');
const renderer = canvas ? new KitchenRenderer(canvas) : null;
const audio = new KitchenAudio();
let screen = 'title', run = null, track = TRACKS[0], trackId = track?.id || '', pausedFrom = 'play', pausedHolds = new Set(), reducedMotion = globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches || false;
const held = new Set();

function trackRecord(id, difficulty = settings.difficulty) { return records[`${id}:${difficulty}`] || null; }
function unlocked(index) { return index === 0 || TRACKS.slice(0, index).every(item => Object.values(records).some(record => record && typeof record === 'object' && !Array.isArray(record) && record.trackId === item.id && record.status === 'won')); }
function persist() { safeWrite(RECORD_KEY, records); safeWrite(SETTINGS_KEY, settings); }
function setScreen(next) { screen = next; document.querySelectorAll('[data-screen]').forEach(node => node.classList.toggle('active', node.dataset.screen === next)); if (next !== 'play' && next !== 'pause' && next !== 'results') renderer?.draw(run, track, run?.time || 0, reducedMotion); }
function formatTime(value) { const seconds = Math.max(0, Math.floor(Number(value) || 0)); return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }
function updateSettingsFromUi() { const difficulty = document.getElementById('difficulty')?.value; if (difficulty === 'normal' || difficulty === 'relaxed') settings.difficulty = difficulty; const volumeValue = Number(document.getElementById('volume')?.value ?? settings.volume); if (Number.isFinite(volumeValue)) settings.volume = Math.max(0, Math.min(1, volumeValue)); const offsetValue = Number(document.getElementById('offset')?.value ?? settings.offset); if (Number.isFinite(offsetValue)) settings.offset = Math.max(-200, Math.min(200, offsetValue)); const volume = document.getElementById('volume'); if (volume) volume.value = settings.volume; const offset = document.getElementById('offset'); if (offset) offset.value = settings.offset; audio.setVolume(settings.volume); audio.setMuted(settings.muted); persist(); }

function renderTrackList() {
  const list = document.getElementById('track-list'); if (!list) return;
  list.innerHTML = TRACKS.map((item, index) => { const record = trackRecord(item.id); const isOpen = unlocked(index); return `<article class="track-card ${isOpen ? '' : 'locked'}" style="--track:${item.colors?.[0] || '#e34e35'}"><div class="track-meta">SERVICE ${String(index + 1).padStart(2, '0')} · ${item.bpm || '—'} BPM</div><h3>${item.name}</h3><p>${item.subtitle || item.description || ''}</p><div class="track-meta">${record ? `${record.rank} · ${Math.round((record.accuracy || 0) * 100)}% · ${record.score || 0}` : (isOpen ? 'NEW MENU' : 'LOCKED')}</div><button class="primary" data-action="choose-track" data-track="${item.id}" ${isOpen ? '' : 'disabled'}>${isOpen ? '서비스 준비' : '잠김'} <span>ENTER</span></button></article>`; }).join('');
}
function syncSettingsUi() { const difficulty = document.getElementById('difficulty'); if (difficulty) difficulty.value = settings.difficulty; const volume = document.getElementById('volume'); if (volume) volume.value = settings.volume; const offset = document.getElementById('offset'); if (offset) offset.value = settings.offset; const mute = document.getElementById('mute-button'); if (mute) mute.textContent = settings.muted ? '소리 꺼짐' : '소리 켜짐'; }

async function begin(id = trackId, difficulty = settings.difficulty) {
  renderer?.reset(); pausedHolds.clear(); document.getElementById('judgement').textContent = ''; document.getElementById('error-ms').textContent = '';
  const selected = getTrack(id) || TRACKS[0]; track = selected; trackId = selected.id; settings.difficulty = difficulty === 'relaxed' ? 'relaxed' : 'normal'; updateSettingsFromUi(); held.clear(); run = createRun(track, settings.difficulty); const started = await audio.start(track); if (!started) { run = null; setScreen('title'); const error = document.getElementById('app-error'); if (error) error.textContent = '오디오를 시작할 수 없습니다. 브라우저의 오디오 권한을 확인한 뒤 다시 시도하세요.'; return; } const error = document.getElementById('app-error'); if (error) error.textContent = ''; setScreen('play'); document.getElementById('play-course').textContent = `SERVICE ${String(TRACKS.indexOf(track) + 1).padStart(2, '0')}`; document.getElementById('play-song').textContent = track.name; document.getElementById('dish-count').textContent = `0 / ${Math.ceil((track.recipes || []).length * (DIFFICULTIES[settings.difficulty]?.requiredRatio || .65))}`; }
async function pauseGame() { if (screen !== 'play' || !run) return; pausedHolds = new Set(run.notes.filter(note => note.status === 'holding').map(note => note.lane)); run.held = run.held.map((value, lane) => pausedHolds.has(lane) ? value : false); held.clear(); await audio.pause(); pausedFrom = 'play'; setScreen('pause'); }
async function resumeGame() { if (screen !== 'pause') return; await audio.resume(); setScreen(pausedFrom); }
async function stopToTitle() { held.clear(); audio.stop(); run = null; setScreen('title'); }
function finishRun() { if (!run || !['won', 'lost'].includes(run.status)) return; const result = summary(run); audio.stop(); if (run.status === 'won') { const key = `${track.id}:${settings.difficulty}`, old = records[key]; if (!old || result.score > old.score) records[key] = { ...result, trackId: track.id, difficulty: settings.difficulty }; persist(); } showResults(result); }
function showResults(result) {
  const finale = TRACKS.indexOf(track) === TRACKS.length - 1;
  document.getElementById('result-title').textContent = result.status === 'won' ? (finale ? '심야 주방의 마지막 접시' : '접시가 완성됐습니다') : '서비스가 중단됐습니다';
  document.getElementById('result-rank').textContent = result.rank;
  document.getElementById('result-score').textContent = String(result.score || 0).padStart(6, '0');
  document.getElementById('result-accuracy').textContent = `${Math.round((result.accuracy || 0) * 100)}%`;
  document.getElementById('result-dishes').textContent = `${result.delivered} / ${result.total}`;
  document.getElementById('result-combo').textContent = `×${result.maxCombo || 0}`;
  document.getElementById('result-message').textContent = result.status === 'won' ? (finale ? '마지막 주문의 불이 꺼지고, 주방의 밤이 끝났습니다.' : '박자가 접시의 온도가 됐어요. 다음 서비스가 기다립니다.') : '손님이 떠나기 전에 다시 불을 올려보세요.';
  const next = document.getElementById('result-next'); if (next) next.hidden = result.status !== 'won' || finale || !unlocked(TRACKS.indexOf(track) + 1);
  setScreen('results');
}

function updateHud() {
  if (!run) return; const result = run; document.getElementById('score').textContent = String(result.score || 0).padStart(6, '0'); document.getElementById('combo').textContent = `×${result.combo || 0}`; document.getElementById('patience').textContent = Math.max(0, Math.round(result.patience ?? 100)); document.querySelector('.patience-stat em')?.style.setProperty('--patience', String(Math.max(0, Math.min(1, (result.patience ?? 100) / 100)))); document.getElementById('time-readout').textContent = formatTime(result.time); const remaining = Math.max(0, (track?.duration || 0) - (result.time || 0)); document.getElementById('remaining-time').textContent = formatTime(remaining); const next = (result.recipes || []).find(recipe => recipe.status === 'pending'); if (next) { document.getElementById('dish-name').textContent = next.name || `DISH ${next.id + 1}`; const total = next.noteIds?.length || 0, complete = (next.noteIds || []).filter(id => result.notes?.find(note => note.id === id)?.status === 'hit').length; document.getElementById('dish-progress').textContent = `재료 ${complete} / ${total}`; } const required = Math.ceil((result.recipes || []).length * (DIFFICULTIES[result.difficulty]?.requiredRatio || .65)); document.getElementById('dish-count').textContent = `${result.delivered || 0} / ${required}`; const last = result.lastJudgement; if (last) { const label = typeof last === 'string' ? last : last.judgement || last.type || ''; document.getElementById('judgement').textContent = String(label).toUpperCase(); } }
function showEvent(event) { renderer?.addEvent(event); if (event.type === 'hit') audio.hit(event.lane, event.judgement); if (event.type === 'dish') audio.dish(event.served, event.quality); const output = document.getElementById('judgement'); const error = document.getElementById('error-ms'); if (event.judgement) { output.textContent = event.judgement.toUpperCase(); error.textContent = event.error == null ? '' : `${event.error > 0 ? '+' : ''}${Math.round(event.error * 1000)} ms`; } else if (event.type === 'miss' || event.type === 'ghost') { output.textContent = event.type === 'ghost' ? 'TOO SOON' : 'MISS'; error.textContent = ''; } }

function pressLane(lane) { if (screen !== 'play' || !run || held.has(lane)) return; held.add(lane); const now = audio.now() + settings.offset / 1000; for (const event of press(run, lane, now) || []) showEvent(event); updateHud(); }
function releaseLane(lane) { if (!run || !held.has(lane)) return; held.delete(lane); if (screen !== 'play') return; const now = audio.now() + settings.offset / 1000; for (const event of release(run, lane, now) || []) showEvent(event); }
function onKeyDown(event) { const key = event.key.toLowerCase(); if (key === 'escape' && !event.repeat) { if (screen === 'play') pauseGame(); else if (screen === 'pause') resumeGame(); return; } if (key === 'm' && !event.repeat) { settings.muted = !settings.muted; audio.setMuted(settings.muted); syncSettingsUi(); persist(); return; } if (key === 'enter' && !event.repeat) { if (screen === 'title') begin(); else if (screen === 'song-select') begin(trackId); else if (screen === 'results') begin(trackId); else if (screen === 'pause') resumeGame(); return; } if (screen !== 'play') return; const lane = key === 'd' ? 0 : key === 'f' ? 1 : key === 'j' ? 2 : key === 'k' ? 3 : key === ' ' ? 4 : -1; if (lane >= 0) { event.preventDefault(); if (!event.repeat) pressLane(lane); } }
function onKeyUp(event) { const key = event.key.toLowerCase(); const lane = key === 'd' ? 0 : key === 'f' ? 1 : key === 'j' ? 2 : key === 'k' ? 3 : key === ' ' ? 4 : -1; if (lane >= 0) { event.preventDefault(); releaseLane(lane); } }
function bindTouch(button) { const lane = Number(button.dataset.lane); const end = event => { event.preventDefault(); releaseLane(lane); button.classList.remove('held'); }; button.addEventListener('pointerdown', event => { event.preventDefault(); try { button.setPointerCapture(event.pointerId); } catch (_) {} button.classList.add('held'); pressLane(lane); }); button.addEventListener('pointerup', end); button.addEventListener('pointercancel', end); button.addEventListener('lostpointercapture', end); }

document.addEventListener('keydown', onKeyDown, { passive: false }); document.addEventListener('keyup', onKeyUp, { passive: false }); window.addEventListener('blur', () => { held.clear(); if (screen === 'play') pauseGame(); }); window.addEventListener('resize', () => renderer?.resize()); document.querySelectorAll('.touch-controls button').forEach(bindTouch);
document.addEventListener('click', event => { const action = event.target.closest('[data-action]')?.dataset.action; if (!action) return; const node = event.target.closest('[data-action]'); if (action === 'start') begin(TRACKS[0]?.id); else if (action === 'song-select') { renderTrackList(); syncSettingsUi(); setScreen('song-select'); } else if (action === 'choose-track') { trackId = node.dataset.track; begin(trackId); } else if (action === 'pause') pauseGame(); else if (action === 'resume') resumeGame(); else if (action === 'restart' || action === 'retry') begin(trackId); else if (action === 'next') { const next = TRACKS[TRACKS.indexOf(track) + 1]; if (next) { trackId = next.id; begin(trackId); } } else if (action === 'back') { if (screen === 'help' || screen === 'song-select') setScreen('title'); else { renderTrackList(); syncSettingsUi(); setScreen('song-select'); } } else if (action === 'title') stopToTitle(); else if (action === 'mute') { settings.muted = !settings.muted; audio.setMuted(settings.muted); syncSettingsUi(); persist(); } else if (action === 'help') setScreen('help'); });
document.getElementById('difficulty')?.addEventListener('change', updateSettingsFromUi); document.getElementById('volume')?.addEventListener('input', updateSettingsFromUi); document.getElementById('offset')?.addEventListener('change', updateSettingsFromUi); syncSettingsUi(); audio.setVolume(settings.volume); audio.setMuted(settings.muted); renderTrackList();

function frame() { if (screen === 'play' && run) { const now = audio.now() + settings.offset / 1000; for (const event of advance(run, now) || []) showEvent(event); for (const lane of [...pausedHolds]) { if (!run.notes.some(note => note.status === 'holding' && note.lane === lane)) { for (const event of release(run, lane, now) || []) showEvent(event); pausedHolds.delete(lane); } } updateHud(); audio.update(); renderer?.draw(run, track, run.time, reducedMotion); if (run.status !== 'playing') finishRun(); } else if (screen === 'title' || screen === 'song-select' || screen === 'help') renderer?.draw(run, track, run?.time || 0, reducedMotion); requestAnimationFrame(frame); }
Object.defineProperty(window, '__sizzle', { configurable: false, enumerable: true, get: () => ({ get screen() { return screen; }, get run() { return clone(run); }, get trackId() { return trackId; }, get settings() { return clone(settings); }, get records() { return clone(records); }, get audioTime() { return audio.now(); }, get renderStats() { return renderer?.stats() || {}; }, get ready() { return true; } }) });
requestAnimationFrame(frame);
